###Component options:
  --disable-avdevice       						#disable libavdevice build
  --disable-avcodec        						#disable libavcodec build
  --disable-avformat       						#disable libavformat build
  --disable-swresample     						#disable libswresample build
  --disable-swscale        						#disable libswscale build
  --disable-postproc       						#disable libpostproc build
  --disable-avfilter       						#disable libavfilter build
  --enable-avresample      						#enable libavresample build [no]
  --disable-pthreads       						#disable pthreads [autodetect]
  --disable-w32threads     						#disable Win32 threads [autodetect]
  --disable-os2threads     						#disable OS/2 threads [autodetect]
  --disable-network        						#disable network support [no]
  --disable-dct            						#disable DCT code
  --disable-dwt            						#disable DWT code
  --disable-error-resilience					#disable error resilience code
  --disable-lsp            						#disable LSP code
  --disable-lzo            						#disable LZO decoder code
  --disable-mdct           						#disable MDCT code
  --disable-rdft           						#disable RDFT code
  --disable-fft            						#disable FFT code
  --disable-faan           						#disable floating point AAN (I)DCT code
  --disable-pixelutils     						#disable pixel utils in libavutil

###Individual component options:
  --disable-everything     						#disable all components listed below
  --disable-encoder=NAME   						#disable encoder NAME
  --enable-encoder=NAME    						#enable encoder NAME
  --disable-encoders       						#disable all encoders
  --disable-decoder=NAME   						#disable decoder NAME
  --enable-decoder=NAME    						#enable decoder NAME
  --disable-decoders       						#disable all decoders
  --disable-hwaccel=NAME   						#disable hwaccel NAME
  --enable-hwaccel=NAME    						#enable hwaccel NAME
  --disable-hwaccels       						#disable all hwaccels
  --disable-muxer=NAME     						#disable muxer NAME
  --enable-muxer=NAME      						#enable muxer NAME
  --disable-muxers         						#disable all muxers
  --disable-demuxer=NAME   						#disable demuxer NAME
  --enable-demuxer=NAME    						#enable demuxer NAME
  --disable-demuxers       						#disable all demuxers
  --enable-parser=NAME     						#enable parser NAME
  --disable-parser=NAME    						#disable parser NAME
  --disable-parsers        						#disable all parsers
  --enable-bsf=NAME        						#enable bitstream filter NAME
  --disable-bsf=NAME       						#disable bitstream filter NAME
  --disable-bsfs           						#disable all bitstream filters
  --enable-protocol=NAME   						#enable protocol NAME
  --disable-protocol=NAME  						#disable protocol NAME
  --disable-protocols      						#disable all protocols
  --enable-indev=NAME      						#enable input device NAME
  --disable-indev=NAME     						#disable input device NAME
  --disable-indevs         						#disable input devices
  --enable-outdev=NAME     						#enable output device NAME
  --disable-outdev=NAME    						#disable output device NAME
  --disable-outdevs        						#disable output devices
  --disable-devices        						#disable all devices
  --enable-filter=NAME     						#enable filter NAME
  --disable-filter=NAME    						#disable filter NAME
  --disable-filters        						#disable all filters
