###External library support:
  export FF_CFG="$FFCFG --enable-avisynth"        						#enable reading of AviSynth script files [no]
  export FF_CFG="$FFCFG --disable-bzlib"          						#disable bzlib [autodetect]
  export FF_CFG="$FFCFG --enable-chromaprint"     						#enable audio fingerprinting with chromaprint [no]
  export FF_CFG="$FFCFG --enable-frei0r"          						#enable frei0r video filtering [no]
  export FF_CFG="$FFCFG --enable-gcrypt"          						#enable gcrypt, needed for rtmp(t)e support
                           						#if openssl, librtmp or gmp is not used [no]
  export FF_CFG="$FFCFG --enable-gmp"             						#enable gmp, needed for rtmp(t)e support
                           						#if openssl or librtmp is not used [no]
  export FF_CFG="$FFCFG --enable-gnutls"          						#enable gnutls, needed for https support
                           						#if openssl is not used [no]
  export FF_CFG="$FFCFG --disable-iconv"          						#disable iconv [autodetect]
  export FF_CFG="$FFCFG --enable-jni"             						#enable JNI support [no]
  export FF_CFG="$FFCFG --enable-ladspa"          						#enable LADSPA audio filtering [no]
  export FF_CFG="$FFCFG --enable-libass"          						#enable libass subtitles rendering,
                           						#needed for subtitles and ass filter [no]
  export FF_CFG="$FFCFG --enable-libbluray"       						#enable BluRay reading using libbluray [no]
  export FF_CFG="$FFCFG --enable-libbs2b"         						#enable bs2b DSP library [no]
  export FF_CFG="$FFCFG --enable-libcaca"         						#enable textual display using libcaca [no]
  export FF_CFG="$FFCFG --enable-libcelt"         						#enable CELT decoding via libcelt [no]
  export FF_CFG="$FFCFG --enable-libcdio"         						#enable audio CD grabbing with libcdio [no]
  export FF_CFG="$FFCFG --enable-libdc1394"       						#enable IIDC-1394 grabbing using libdc1394
                           						#and libraw1394 [no]
  export FF_CFG="$FFCFG --enable-libfdk-aac"      						#enable AAC de/encoding via libfdk-aac [no]
  export FF_CFG="$FFCFG --enable-libflite"        						#enable flite (voice synthesis) support via libflite [no]
  export FF_CFG="$FFCFG --enable-libfontconfig"   						#enable libfontconfig, useful for drawtext filter [no]
  export FF_CFG="$FFCFG --enable-libfreetype"     						#enable libfreetype, needed for drawtext filter [no]
  export FF_CFG="$FFCFG --enable-libfribidi"      						#enable libfribidi, improves drawtext filter [no]
  export FF_CFG="$FFCFG --enable-libgme"          						#enable Game Music Emu via libgme [no]
  export FF_CFG="$FFCFG --enable-libgsm"          						#enable GSM de/encoding via libgsm [no]
  export FF_CFG="$FFCFG --enable-libiec61883"     						#enable iec61883 via libiec61883 [no]
  export FF_CFG="$FFCFG --enable-libilbc"         						#enable iLBC de/encoding via libilbc [no]
  export FF_CFG="$FFCFG --enable-libkvazaar"      						#enable HEVC encoding via libkvazaar [no]
  export FF_CFG="$FFCFG --enable-libmodplug"      						#enable ModPlug via libmodplug [no]
  export FF_CFG="$FFCFG --enable-libmp3lame"      						#enable MP3 encoding via libmp3lame [no]
  export FF_CFG="$FFCFG --enable-libnut"          						#enable NUT (de)muxing via libnut,
                           						#native (de)muxer exists [no]
  export FF_CFG="$FFCFG --enable-libopencore-amrnb"					# enable AMR-NB de/encoding via libopencore-amrnb [no]
  export FF_CFG="$FFCFG --enable-libopencore-amrwb"					# enable AMR-WB decoding via libopencore-amrwb [no]
  export FF_CFG="$FFCFG --enable-libopencv"       						#enable video filtering via libopencv [no]
  export FF_CFG="$FFCFG --enable-libopenh264"     						#enable H.264 encoding via OpenH264 [no]
  export FF_CFG="$FFCFG --enable-libopenjpeg"     						#enable JPEG 2000 de/encoding via OpenJPEG [no]
  export FF_CFG="$FFCFG --enable-libopenmpt"      						#enable decoding tracked files via libopenmpt [no]
  export FF_CFG="$FFCFG --enable-libopus"         						#enable Opus de/encoding via libopus [no]
  export FF_CFG="$FFCFG --enable-libpulse"        						#enable Pulseaudio input via libpulse [no]
  export FF_CFG="$FFCFG --enable-librubberband"   						#enable rubberband needed for rubberband filter [no]
  export FF_CFG="$FFCFG --enable-librtmp"         						#enable RTMP[E] support via librtmp [no]
  export FF_CFG="$FFCFG --enable-libschroedinger" 						#enable Dirac de/encoding via libschroedinger [no]
  export FF_CFG="$FFCFG --enable-libshine"        						#enable fixed-point MP3 encoding via libshine [no]
  export FF_CFG="$FFCFG --enable-libsmbclient"    						#enable Samba protocol via libsmbclient [no]
  export FF_CFG="$FFCFG --enable-libsnappy"       						#enable Snappy compression, needed for hap encoding [no]
  export FF_CFG="$FFCFG --enable-libsoxr"         						#enable Include libsoxr resampling [no]
  export FF_CFG="$FFCFG --enable-libspeex"        						#enable Speex de/encoding via libspeex [no]
  export FF_CFG="$FFCFG --enable-libssh"          						#enable SFTP protocol via libssh [no]
  export FF_CFG="$FFCFG --enable-libtesseract"    						#enable Tesseract, needed for ocr filter [no]
  export FF_CFG="$FFCFG --enable-libtheora"       						#enable Theora encoding via libtheora [no]
  export FF_CFG="$FFCFG --enable-libtwolame"      						#enable MP2 encoding via libtwolame [no]
  export FF_CFG="$FFCFG --enable-libv4l2"         						#enable libv4l2/v4l-utils [no]
  export FF_CFG="$FFCFG --enable-libvidstab"      						#enable video stabilization using vid.stab [no]
  export FF_CFG="$FFCFG --enable-libvo-amrwbenc"  						#enable AMR-WB encoding via libvo-amrwbenc [no]
  export FF_CFG="$FFCFG --enable-libvorbis"       						#enable Vorbis en/decoding via libvorbis,
                           						#native implementation exists [no]
  export FF_CFG="$FFCFG --enable-libvpx"          						#enable VP8 and VP9 de/encoding via libvpx [no]
  export FF_CFG="$FFCFG --enable-libwavpack"      						#enable wavpack encoding via libwavpack [no]
  export FF_CFG="$FFCFG --enable-libwebp"         						#enable WebP encoding via libwebp [no]
  export FF_CFG="$FFCFG --enable-libx264"         						#enable H.264 encoding via x264 [no]
  export FF_CFG="$FFCFG --enable-libx265"         						#enable HEVC encoding via x265 [no]
  export FF_CFG="$FFCFG --enable-libxavs"         						#enable AVS encoding via xavs [no]
  export FF_CFG="$FFCFG --enable-libxcb"          						#enable X11 grabbing using XCB [autodetect]
  export FF_CFG="$FFCFG --enable-libxcb-shm"      						#enable X11 grabbing shm communication [autodetect]
  export FF_CFG="$FFCFG --enable-libxcb-xfixes"   						#enable X11 grabbing mouse rendering [autodetect]
  export FF_CFG="$FFCFG --enable-libxcb-shape"    						#enable X11 grabbing shape rendering [autodetect]
  export FF_CFG="$FFCFG --enable-libxvid"         						#enable Xvid encoding via xvidcore,
                           						#native MPEG-4/Xvid encoder exists [no]
  export FF_CFG="$FFCFG --enable-libzimg"         						#enable z.lib, needed for zscale filter [no]
  export FF_CFG="$FFCFG --enable-libzmq"          						#enable message passing via libzmq [no]
  export FF_CFG="$FFCFG --enable-libzvbi"         						#enable teletext support via libzvbi [no]
  export FF_CFG="$FFCFG --disable-lzma"           						#disable lzma [autodetect]
  export FF_CFG="$FFCFG --enable-decklink"        						#enable Blackmagic DeckLink I/O support [no]
  export FF_CFG="$FFCFG --enable-mediacodec"      						#enable Android MediaCodec support [no]
  export FF_CFG="$FFCFG --enable-netcdf"          						#enable NetCDF, needed for sofalizer filter [no]
  export FF_CFG="$FFCFG --enable-openal"          						#enable OpenAL 1.1 capture support [no]
  export FF_CFG="$FFCFG --enable-opencl"          						#enable OpenCL code
  export FF_CFG="$FFCFG --enable-opengl"          						#enable OpenGL rendering [no]
  export FF_CFG="$FFCFG --enable-openssl"         						#enable openssl, needed for https support
                           						#if gnutls is not used [no]
  export FF_CFG="$FFCFG --disable-schannel"       						#disable SChannel SSP, needed for TLS support on
                           						#Windows if openssl and gnutls are not used [autodetect]
  export FF_CFG="$FFCFG --disable-sdl2"           						#disable sdl2 [autodetect]
  export FF_CFG="$FFCFG --disable-securetransport"						# disable Secure Transport, needed for TLS support
                           						#on OSX if openssl and gnutls are not used [autodetect]
  export FF_CFG="$FFCFG --disable-xlib"           						#disable xlib [autodetect]
  export FF_CFG="$FFCFG --disable-zlib"           						#disable zlib [autodetect]
